#!/bin/bash
# wst-keys - manages wstunnel keys (websocket path prefixes) on the carrier server.
# Installed on the carrier server as /usr/local/sbin/wst-keys and invoked by `torii wst ...` over ssh
# (the client pushes and reinstalls this file before every call, so both ends never drift apart).
#
#   wst-keys status              layout (old / new), key count, fingerprint of each key (first 12 hex
#                                of sha256). Never prints keys
#   wst-keys add      < key      add a key, keep all existing ones - hot reload, no wstunnel restart,
#                                no tunnel drop
#   wst-keys keep     < keys     keep only the keys given on stdin (one per line, at least one, each
#                                must already exist)
#   wst-keys init                fresh install (server/install.sh): render restrict.yaml and the Caddy
#                                snippet, self-test them
#   wst-keys selftest            full path through Caddy with the newest key, like a real client
#   wst-keys selfcheck-or-rollback STAMP   used internally by migrate
#   wst-keys migrate             one-time: move from "single key hardcoded in the unit + Caddyfile" to
#                                this scheme. Restarts wstunnel once (after 2s, detached from ssh),
#                                self-checks after the restart and rolls back on failure
#
# ── why multiple keys side by side ──────────────────────────
# The old approach was a single swap: server switches key -> restart -> client writes the new key.
# Once the client was killed before its step (the rotating ssh ran through the very tunnel being
# restarted and hung until a 180s timeout); the two ends no longer matched and every variant got 404.
# Now: add the new key first (old and new both valid) -> client switches -> old key removed after a
# grace period. An interruption at any step leaves at least one common key.
#
# ── keys only via stdin ─────────────────────────────────────────────
# The old script used `sudo NEW_SECRET=... bash -s`; sudo logs ENV= verbatim to the journal, leaving
# the key in plain text in the server logs.
#
# Authoritative list: /etc/wstunnel/keys (600, one per line, newest last). Generated from it:
#   /etc/wstunnel/restrict.yaml   wstunnel --restrict-config; wstunnel reloads it when the file changes
#   /etc/caddy/wst-paths.caddy    @wst matcher imported by the Caddyfile (caddy reload is graceful)
set -euo pipefail
[ "$(id -u)" -eq 0 ] || { echo "must run as root" >&2; exit 1; }

D=/etc/wstunnel
KEYS=$D/keys
TARGET=$D/target            # e.g. "198.51.100.20:51820"; copied from the old unit's --restrict-to during migrate
RY=$D/restrict.yaml
CS=/etc/caddy/wst-paths.caddy
CF=/etc/caddy/Caddyfile
UNIT=/etc/systemd/system/wstunnel-server.service
WST=/usr/local/bin/wstunnel
MAX_KEYS=3
# Full-path self-check entry: through Caddy (:443, TLS), same as a real client. A 404 can come from the
# Caddy layer, which testing wstunnel alone would miss
FRONT=wss://127.0.0.1:443

# Caddy routes by Host; install.sh writes the domain. An array, so "Host: name" stays one argument.
HOSTHDR=$(cat "$D/domain" 2>/dev/null || true)
HARGS=(); [ -n "$HOSTHDR" ] && HARGS=(-H "Host: $HOSTHDR")
die() { echo "$*" >&2; exit 1; }
fp() { printf '%s' "$1" | sha256sum | cut -c1-12; }
valid() { [[ "$1" =~ ^[A-Za-z0-9_-]{24,}$ ]]; }
migrated() { grep -q -- '--restrict-config' "$UNIT" 2>/dev/null; }

read_stdin_keys() {
    local k out=()
    while IFS= read -r k || [ -n "$k" ]; do
        k=${k//$'\r'/}
        [ -z "$k" ] && continue
        valid "$k" || die "invalid key on stdin (must match [A-Za-z0-9_-]{24,})"
        out+=("$k")
    done
    [ ${#out[@]} -gt 0 ] || die "no keys on stdin"
    printf '%s\n' "${out[@]}"
}

# Render restrict.yaml and the Caddy snippet from keys to the given paths
render_yaml() {  # $1 = output file
    local host port k
    host=${T%:*}; port=${T##*:}   # target is an IP, so cidr /32 pins it; no host regex (\. is an invalid escape in YAML double quotes)
    {
        echo "# generated by wst-keys, do not edit; authoritative list is $KEYS"
        echo "restrictions:"
        while IFS= read -r k; do
            [ -z "$k" ] && continue
            cat <<EOF
  - name: "key-$(fp "$k")"
    description: "toriid wstunnel key"
    match:
      - !PathPrefix "^$k\$"
    allow:
      - !Tunnel
        protocol:
          - Udp
        port:
          - $port
        cidr:
          - $host/32
EOF
        done < "$KEYS"
    } > "$1"
}
render_caddy() {  # $1 = output file
    local paths="" k
    while IFS= read -r k; do [ -n "$k" ] && paths+=" /$k/*"; done < "$KEYS"
    printf '# generated by wst-keys, do not edit\n@wst path%s\n' "$paths" > "$1"
}

# Validate the yaml with a temporary wstunnel instance + a real client: this key is accepted, a random
# one is rejected. (A hand-made curl upgrade request gets a 400 before the key check, valid key or not -
# observed; only a real client works.)
yaml_selftest() {  # $1 = yaml, $2 = a key that must be accepted
    local sp good bad
    "$WST" server --restrict-config "$1" ws://127.0.0.1:18091 >/dev/null 2>&1 &
    sp=$!
    sleep 1.5
    if ! kill -0 "$sp" 2>/dev/null; then echo "temporary wstunnel failed to start (bad yaml)" >&2; return 1; fi
    good=$(client_try "$2" ws://127.0.0.1:18091); bad=$(client_try "not-a-key-$(date +%s%N)" ws://127.0.0.1:18091)
    kill "$sp" 2>/dev/null; wait "$sp" 2>/dev/null || true
    [ "$good" = accepted ] || { echo "temporary instance rejected the key ($good)" >&2; return 1; }
    [ "$bad" != accepted ] || { echo "temporary instance accepted a random key" >&2; return 1; }
}
client_try() {  # $1 = key, $2 = ws://... -> accepted | rejection reason
    local log cp
    log=$(mktemp)
    "$WST" client --http-upgrade-path-prefix "$1" "${HARGS[@]}" -L "udp://127.0.0.1:18300:$T?timeout_sec=5" "$2" >"$log" 2>&1 &
    cp=$!
    sleep 1
    printf 'x' > /dev/udp/127.0.0.1/18300 2>/dev/null || true
    sleep 1.5
    kill "$cp" 2>/dev/null; wait "$cp" 2>/dev/null || true
    if grep -q "Invalid status code" "$log"; then grep -o "Invalid status code: [0-9]*" "$log" | head -n1
    elif grep -qiE "error|failed" "$log"; then echo "error"
    else echo accepted; fi
    rm -f "$log"
}

# Install the rendered yaml and caddy snippet. add: yaml first, then caddy (wstunnel already accepts the
# new path by the time caddy starts forwarding it); remove: the reverse (caddy stops forwarding old paths first)
install_rendered() {  # $1 = add|remove
    local ty tc stamp r
    ty=$(mktemp "$D/.restrict.XXXX"); tc=$(mktemp /etc/caddy/.wst-paths.XXXX)
    render_yaml "$ty"; render_caddy "$tc"
    yaml_selftest "$ty" "$(tail -n1 "$KEYS")" || { rm -f "$ty" "$tc"; return 1; }
    stamp=$(date +%Y%m%d-%H%M%S)
    [ -f "$CS" ] && cp -a "$CS" "$CS.bak.$stamp"
    [ -f "$RY" ] && cp -a "$RY" "$RY.bak.$stamp"
    chmod 600 "$ty"; chown root:root "$ty"
    chmod 640 "$tc"; chown root:caddy "$tc" 2>/dev/null || chmod 644 "$tc"
    if [ "$1" = add ]; then
        mv -f "$ty" "$RY"; sleep 1
        mv -f "$tc" "$CS"
        caddy validate --adapter caddyfile --config "$CF" >/dev/null 2>&1 || { cp -a "$CS.bak.$stamp" "$CS" 2>/dev/null || true; die "Caddyfile validation failed, Caddy snippet rolled back (wstunnel accepting one extra key is harmless)"; }
        systemctl reload caddy
        sleep 1
        r=$(client_try "$(tail -n1 "$KEYS")" "$FRONT")
        if [ "$r" != accepted ]; then
            cp -a "$CS.bak.$stamp" "$CS" 2>/dev/null || true; cp -a "$RY.bak.$stamp" "$RY" 2>/dev/null || true
            systemctl reload caddy
            echo "after install, full path through Caddy fails ($r), both rolled back" >&2; return 1
        fi
    else
        mv -f "$tc" "$CS"
        caddy validate --adapter caddyfile --config "$CF" >/dev/null 2>&1 || { cp -a "$CS.bak.$stamp" "$CS" 2>/dev/null || true; rm -f "$ty"; die "Caddyfile validation failed, rolled back, no key removed"; }
        systemctl reload caddy
        mv -f "$ty" "$RY"
        sleep 2
        r=$(client_try "$(tail -n1 "$KEYS")" "$FRONT")
        if [ "$r" != accepted ]; then
            cp -a "$CS.bak.$stamp" "$CS" 2>/dev/null || true; cp -a "$RY.bak.$stamp" "$RY" 2>/dev/null || true
            systemctl reload caddy
            echo "after removal, remaining key fails through Caddy ($r), both rolled back" >&2; return 1
        fi
    fi
    ls -1t "$CS".bak.* 2>/dev/null | tail -n +4 | xargs -r rm -f
    ls -1t "$RY".bak.* 2>/dev/null | tail -n +4 | xargs -r rm -f
}

cmd=${1:-status}
case "$cmd" in
status)
    if migrated; then echo "layout new"; else echo "layout old"; fi
    if [ -s "$KEYS" ]; then
        echo "keys $(grep -c . "$KEYS")"
        while IFS= read -r k; do [ -n "$k" ] && echo "fp $(fp "$k")"; done < "$KEYS"
    elif [ -s "$D/path-secret" ]; then
        echo "keys 1"; echo "fp $(fp "$(tr -d '\r\n' < "$D/path-secret")")"
    else
        echo "keys 0"
    fi
    systemctl is-active --quiet wstunnel-server && echo "wstunnel active" || echo "wstunnel inactive"
    ;;
add)
    migrated || die "server still has the old layout - run torii wst migrate first"
    T=$(cat "$TARGET")
    new=$(read_stdin_keys | tail -n1)
    if grep -qxF -- "$new" "$KEYS"; then echo "ok already $(fp "$new")"; exit 0; fi
    cp -a "$KEYS" "$KEYS.prev"
    printf '%s\n' "$new" >> "$KEYS"
    # over the limit: drop the oldest first (normally keep prunes beforehand; this is a backstop)
    n=$(grep -c . "$KEYS"); if [ "$n" -gt $MAX_KEYS ]; then tail -n $MAX_KEYS "$KEYS" > "$KEYS.tmp" && mv -f "$KEYS.tmp" "$KEYS"; fi
    chmod 600 "$KEYS"
    if ! install_rendered add; then cp -a "$KEYS.prev" "$KEYS"; die "installing the new key failed, key list restored"; fi
    printf '%s\n' "$new" > "$D/path-secret"; chmod 600 "$D/path-secret"
    echo "ok added $(fp "$new") keys=$(grep -c . "$KEYS")"
    ;;
keep)
    migrated || die "server still has the old layout - run torii wst migrate first"
    T=$(cat "$TARGET")
    want=$(read_stdin_keys)
    while IFS= read -r k; do grep -qxF -- "$k" "$KEYS" || die "key to keep $(fp "$k") is not on the server - refusing (could end up with no keys)"; done <<< "$want"
    cp -a "$KEYS" "$KEYS.prev"
    # keep original order, only the wanted keys
    grep -xF -f <(printf '%s\n' "$want") "$KEYS.prev" > "$KEYS" || true
    chmod 600 "$KEYS"
    [ -s "$KEYS" ] || { cp -a "$KEYS.prev" "$KEYS"; die "would leave no keys, refusing"; }
    if ! install_rendered remove; then cp -a "$KEYS.prev" "$KEYS"; die "removing keys failed, key list restored"; fi
    echo "ok kept $(grep -c . "$KEYS")"
    ;;
init)
    # Fresh install (server/install.sh): keys and target already written; render both files and self-check
    # the yaml with a temporary instance. Does not touch the unit or the Caddyfile.
    [ -s "$KEYS" ] && [ -s "$TARGET" ] || die "init needs $KEYS and $TARGET"
    T=$(cat "$TARGET")
    render_yaml "$RY"; render_caddy "$CS"
    chmod 600 "$RY"; chmod 640 "$CS"; chown root:caddy "$CS" 2>/dev/null || chmod 644 "$CS"
    yaml_selftest "$RY" "$(tail -n1 "$KEYS")" || die "restrict.yaml self-check failed"
    echo "ok init keys=$(grep -c . "$KEYS")"
    ;;
selftest)
    # Full path through Caddy with the newest key, exactly like a real client.
    T=$(cat "$TARGET")
    r=$(client_try "$(tail -n1 "$KEYS")" "$FRONT")
    [ "$r" = accepted ] && echo "ok selftest" || die "selftest failed: $r"
    ;;
migrate)
    if migrated; then echo "ok already migrated"; exit 0; fi
    old=$(tr -d '\r\n' < "$D/path-secret" 2>/dev/null || true)
    valid "$old" || die "no valid key in $D/path-secret"
    grep -q -- "--restrict-http-upgrade-path-prefix $old" "$UNIT" || die "current key not found in the unit, unexpected layout, not touching anything"
    grep -q -- "handle /$old/\*" "$CF" || die "current key not found in the Caddyfile, not touching anything"
    T=$(grep -o -- '--restrict-to [0-9.]*:[0-9]*' "$UNIT" | awk '{print $2}')
    [[ "$T" =~ ^[0-9.]+:[0-9]+$ ]] || die "--restrict-to host:port not found in the unit"
    listen=$(grep -o 'ws://127\.0\.0\.1:[0-9]*' "$UNIT" | head -n1)
    [ -n "$listen" ] || die "ws://127.0.0.1:PORT not found in the unit"
    stamp=$(date +%Y%m%d-%H%M%S)
    cp -a "$UNIT" "$UNIT.bak.$stamp"; cp -a "$CF" "$CF.bak.$stamp"
    ( umask 077; printf '%s\n' "$old" > "$KEYS"; printf '%s\n' "$T" > "$TARGET" )
    render_yaml "$RY"; render_caddy "$CS"
    chmod 600 "$RY"; chmod 640 "$CS"; chown root:caddy "$CS" 2>/dev/null || chmod 644 "$CS"
    yaml_selftest "$RY" "$old" || { rm -f "$KEYS" "$TARGET" "$RY" "$CS"; die "render / self-check failed, unit and Caddyfile untouched"; }
    # Caddyfile: handle /<old>/* { -> import snippet + handle @wst {
    sed -i "s|^\(\s*\)handle /$old/\*|\1import $CS\n\1handle @wst|" "$CF"
    if ! caddy validate --adapter caddyfile --config "$CF" >/dev/null 2>&1; then
        cp -a "$CF.bak.$stamp" "$CF"; die "new Caddyfile failed validation, rolled back, wstunnel untouched"
    fi
    # unit: replace the whole ExecStart with --restrict-config (other lines unchanged)
    awk -v listen="$listen" -v ry="$RY" -v wst="$WST" '
        /^ExecStart=/ { print "ExecStart=" wst " server --restrict-config " ry " " listen; skip = /\\$/; next }
        skip { skip = /\\$/; next }
        { print }' "$UNIT.bak.$stamp" > "$UNIT"
    systemctl daemon-reload
    systemctl reload caddy
    # Restart after 2s, detached from this ssh session (the caller may be inside this tunnel); afterwards
    # self-check the live instance with a real client and roll everything back on failure
    install -m 700 "$0" "$D/.wst-keys-migrate" 2>/dev/null || cp -a "$(readlink -f "$0")" "$D/.wst-keys-migrate"
    systemd-run --quiet --on-active=2 --unit="wst-migrate-$stamp" /bin/bash -c \
        "systemctl restart wstunnel-server; sleep 4; $D/.wst-keys-migrate selfcheck-or-rollback $stamp; rm -f $D/.wst-keys-migrate"
    echo "ok migrating $stamp (wstunnel-server restarts in 2s, self-check 4s later; see journalctl -t wst-keys)"
    ;;
selfcheck-or-rollback)
    stamp=${2:?}
    T=$(cat "$TARGET")
    r=$(client_try "$(tail -n1 "$KEYS")" "$FRONT")
    if systemctl is-active --quiet wstunnel-server && [ "$r" = accepted ]; then
        logger -t wst-keys "migrate ok: live instance accepts the current key"
    else
        logger -t wst-keys "migrate self-check failed ($r) - rolling back to $stamp"
        cp -a "$UNIT.bak.$stamp" "$UNIT"; cp -a "$CF.bak.$stamp" "$CF"
        systemctl daemon-reload; systemctl reload caddy; systemctl restart wstunnel-server
    fi
    ;;
*)
    die "usage: wst-keys status | add < key | keep < keys | init | selftest | migrate"
    ;;
esac
